#!/bin/bash

## Steps to setup your chromebook
echo 'Start from user root'
cd ~

echo 'Clone chromix'
# [ -d chromix-old ] && rm -rf chromix-old
# [ -d .chromix ] && mv .chromix chromix-old
# git clone git@github.com:lockerfish/my-chromix.git .chromix

echo 'Link bash files'
# bash
# ln -sf .chromix/bash/bashrc .bashrc
# ln -sf .chromix/bash/bash_profile .bash_profile
# ln -sf .chromix/bash/bash_aliases .bash_aliases
# ln -sf .chromix/bash/bash_functions .bash_functions
# ln -sf .chromix/bash/bash_logout .bash_logout
# git
# ln -sf .chromix/git/git_completion .git_completion
# ln -sf .chromix/git/gitconfig .gitconfig
# ln -sf .chromix/git/gitignore .gitignore

echo 'Install packages'
# ~/.chromix/chromix-setup
for pkg in $(ls -d ~/.chromix/*/); do
  echo "Installing packages in: ${pkg%%/}";
  if [ -f ${pkg%%/}/setup ]; then
    echo "found"
    ${pkg%%/}/setup;
  else
    echo "not found"
  fi
done
