#!/bin/bash

## Steps to setup your chromebook
echo 'Start from user root'
cd ~

echo 'Clone chromix'
[ -d chromix-old ] && rm -rf chromix-old
[ -d .chromix ] && mv .chromix chromix-old
git clone git@github.com:lockerfish/my-chromix.git .chromix

pkg_install() {
  echo "
/-----------------------------------------------------------/
  APT-GET: Installing $pkg_name
/-----------------------------------------------------------/
  "
  dpkg -s $pkg_name >/dev/null 2>&1

  if [ $? -eq 0 ]; then
    echo "$pkg_name: already installed. Updating..."
    sudo apt-get install --only-upgrade $pkg_name
  else
    sudo apt-get install -y $pkg_name
    echo "$pkg_name: is now installed successfully!"
    sudo apt-get -y update
  fi
}

echo 'Install packages'
for pkg in $(ls -d ~/.chromix/*/); do
  echo "Installing packages in: ${pkg%%/}";
  if [ -f ${pkg%%/}/setup ]; then
    echo "found"
    ${pkg%%/}/setup;
  else
    echo "not found"
  fi
done
