#!/bin/bash

echo "
----------------------------------------------------------------------------
DART SETUP
----------------------------------------------------------------------------
"
pkg_name='dart'

echo "
/-----------------------------------------------------------/
  Adding Google Dart debian package repo and key
  https://www.dartlang.org/tools/sdk#install
  https://flutter.io/setup-linux/#get-sdk
/-----------------------------------------------------------/
"
sudo sh -c 'curl https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
sudo sh -c 'curl https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'

pkg_install