#!/bin/bash

echo "
----------------------------------------------------------------------------
CODE SETUP
----------------------------------------------------------------------------
"
pkg_name='code'

echo "
/-----------------------------------------------------------/
  Adding Microsoft VSCode debian package repo and key
  https://code.visualstudio.com/docs/setup/linux
/-----------------------------------------------------------/
"
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'

pkg_install

code --install-extension Shan.code-settings-sync