#!/bin/bash

echo "
----------------------------------------------------------------------------
NODE SETUP
----------------------------------------------------------------------------
"

pkg_name='nodejs'

echo "
/-----------------------------------------------------------/
  Adding Nodesource debian package repo and key
  https://deb.nodesource.com/setup_12.x
/-----------------------------------------------------------/
"
sudo sh -c "curl -fsSL https://deb.nodesource.com/setup_12.x | sudo -E bash -"

pkg_install
