#!/bin/bash

echo "
----------------------------------------------------------------------------
NODE SETUP
----------------------------------------------------------------------------
"

pkg_name='nodejs'

echo "
/-----------------------------------------------------------/
  Adding Nodesource debian package repo and key
  https://deb.nodesource.com/setup_8.x
/-----------------------------------------------------------/
"
sudo sh -c "curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -"

pkg_install