#!/bin/bash

echo "
----------------------------------------------------------------------------
YARN SETUP
----------------------------------------------------------------------------
"

pkg_name='yarn'

echo "
/-----------------------------------------------------------/
  Adding yarn debian package repo and key
  https://yarnpkg.com/lang/en/docs/install
/-----------------------------------------------------------/
"
sudo sh -c "curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -"
sudo sh -c "echo 'deb https://dl.yarnpkg.com/debian/ stable main' | sudo tee /etc/apt/sources.list.d/yarn.list"

pkg_install
